version: "3.8"
services:
    backend:
        build: ./
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
        networks:
            - app_network

    frontend:
        build: ./frontend
        ports:
            - "5173:80"
        depends_on:
            - backend
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
