version: "3.8"

services:
    backend:
        build: ./
        container_name: backend_service
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
            - DOCKER_HOST=tcp://host.docker.internal:2375
        networks:
            - app_network

    frontend:
        build: ./frontend
        container_name: frontend_service
        ports:
            - "5173:80"
        depends_on:
            - backend
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
